name: Build

on:
  workflow_dispatch:

  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src/

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Threshold=50 /p:ThresholdType=line /p:ThresholdStat=total

      - name: Install ReportGenerator tool
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Merge Coverage Results
        run: reportgenerator "-reports:${{ github.workspace }}/**/coverage.cobertura.xml" "-targetdir:coveragereport" -reporttypes:Cobertura

      - name: Publish Coverage Results
        uses: codecov/codecov-action@v2
        with:
          files: ${{ github.workspace }}/coveragereport/coverage.cobertura.xml
          fail_ci_if_error: true
